apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    srv: api
spec:
  selector:
    srv: api
  type: NodePort
  ports:
   - name: react
     port: 8000
     nodePort: 30001
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    srv: api
  name: ubuntu-ocr
spec:
  containers:
    - name: ubuntu-ocr
      image: kkbankol/ubuntu-ocr
      imagePullPolicy: Always
      stdin: true
      tty: true
      command: ["/bin/bash"]
      # command: ["/usr/bin/python3"]
      # args: ["ocr_server.py"]
